name: BLSM_AI helper

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    types: [opened, closed]
    branches:
      - dev
      - main
  issues:
    types: [opened, closed, reopened]
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install
    
    - name: Install axios
      run: npm install axios

    - name: Excute BLSM script
      run: node .github/scripts/blsm.js
      env:
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        COMMIT_AUTHOR: ${{ github.event.head_commit.author.name }}
        COMMIT_SHA: ${{ github.sha }}
        COMMIT_REF: ${{ github.ref }}
        COMMIT_REPO: ${{ github.repository}}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        ISSUE_TITLE: ${{ github.event.issue.title }}
        ISSUE_BODY: ${{ github.event.issue.body }}
        ISSUE_REPO: ${{ github.repository }}
        ISSUE_ACTION: ${{ github.event.issue.action }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        PR_TITLE: ${{ github.event.pull_request.title }}
        PR_BODY: ${{ github.event.pull_request.body }}
        PR_ACTION: ${{ github.event.pull_request.action }}
        PR_REPO: ${{ github.repository }}
        TIMESTAMP: ${{ github.event.head_commit.timestamp }}
        TYPE: ${{ github.event_name }}
        USER: ${{ github.actor }}
        REPO: ${{ github.repository }}
